[build]
builder = "nixpacks"
buildCommand = "cd /app/backend && mvn clean package"

[deploy]
startCommand = "cd /app && java -jar backend/target/*.jar --server.port=$PORT"

[deploy.healthcheck]
port = 8080
path = "/actuator/health"