[build]
builder = "nixpacks"
buildCommand = "cd /app && mvn clean package"

[deploy]
startCommand = "cd /app && java -jar app/target/InteraktiveDashboard-1.0-SNAPSHOT.jar --server.port=$PORT"

[deploy.healthcheck]
port = 8080
path = "/actuator/health"