[build]
builder = "nixpacks"
buildCommand = "cd backend && mvn clean package"

[deploy]
startCommand = "cd backend && java -jar target/*.jar --server.port=$PORT"

[deploy.healthcheck]
port = 8080
path = "/actuator/health"