[build]
builder = "nixpacks"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "java -jar backend/target/*.jar --server.port=$PORT"

[deploy.healthcheck]
port = 8080
path = "/actuator/health"